pipeline:
  publish:
    image: plugins/docker
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/pipipan/hello
    secrets: [docker_username, docker_password]
    tags: latest
  deploy:
    image: appleboy/drone-ssh
    host: 47.106.8.47
    username: root
    secrets: [ ssh_password ]
    port: 22
    script:
    - cd /root/shell
    - ./deploy.sh hello